[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/tts/*"
  to = "/.netlify/functions/tts/:splat"
  status = 200

[[redirects]]
  from = "/api/video/*"
  to = "/.netlify/functions/video/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

